# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
#

APP_NAME := timerMultiCancelTest
ARDUINO_LIBS := AUnit arduino-timer
CPPFLAGS += -Werror

include $(UNIXHOSTDUINO)
