name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/UnixHostDuino
        #git clone https://github.com/bxparks/AceCommon
        git clone https://github.com/bxparks/AUnit
    - name: Verify examples
      run: |
        make -C examples
    - name: Run tests
      run: |
        make -C tests
        make -C tests runtests

